#!/usr/bin/env python3
"""
Gate: Block 'git add -A' and 'git add .' in Claude Code sessions.

Generated by: harness init

== WHY THIS GATE EXISTS ==

In multi-agent projects, the working directory often contains changes from
multiple agents, build artifacts, lock files, and other unrelated modifications.
When an agent runs 'git add -A' or 'git add .', it stages EVERYTHING — including
other agents' in-progress work, .env files, and build output.

This gate forces agents to stage files explicitly by name:
  git add src/feature.go src/feature_test.go    # Good — explicit
  git add -A                                     # Blocked
  git add .                                      # Blocked

== HOW IT WORKS ==

This is a Claude Code PreToolUse hook. When an agent tries to run a Bash command,
Claude Code sends the command to this script via stdin as JSON. If the command
matches a blanket git-add pattern, the script returns a deny decision that
prevents the command from executing and shows the agent an error message.

== CONFIGURATION ==

- To disable temporarily: set SKIP_GIT_ADD_ALL_GATE=1 in your environment
- To remove permanently: delete this file and remove its entry from settings.json

== HOOK PROTOCOL ==

Input (stdin): JSON with tool_name and tool_input.command
Output (stdout): JSON with hookSpecificOutput.permissionDecision = "deny" to block
Exit 0 always (hooks should not crash Claude Code)
"""
import json
import os
import re
import sys

# Patterns that match blanket git add commands
BLANKET_GIT_ADD_PATTERNS = [
    r'\bgit\s+add\s+(-A|--all)\b',
    r'\bgit\s+add\s+\.(?:\s|$|&&|\||;)',
]


def is_blanket_git_add(command: str) -> bool:
    """Detect if a Bash command uses blanket git add."""
    for pattern in BLANKET_GIT_ADD_PATTERNS:
        if re.search(pattern, command):
            return True
    return False


def main():
    # Escape hatch: set this env var to bypass the gate
    if os.environ.get("SKIP_GIT_ADD_ALL_GATE", "") == "1":
        sys.exit(0)

    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        sys.exit(0)

    if input_data.get("tool_name") != "Bash":
        sys.exit(0)

    command = input_data.get("tool_input", {}).get("command", "")
    if not is_blanket_git_add(command):
        sys.exit(0)

    output = {
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": (
                "BLOCKED: Do not use 'git add -A' or 'git add .'\n\n"
                "In multi-agent projects, the working directory often has unrelated\n"
                "changes from other agents, build artifacts, or sensitive files.\n\n"
                "Stage ONLY the specific files you created or modified:\n"
                "  git add path/to/file1 path/to/file2\n\n"
                "To bypass: set SKIP_GIT_ADD_ALL_GATE=1"
            ),
        }
    }
    print(json.dumps(output))
    sys.exit(0)


if __name__ == "__main__":
    main()
