/**
 * Plugin: skillc Generated File Guard
 *
 * Blocks direct edits to AUTO-GENERATED skillc artifacts.
 *
 * Triggered by: tool.execute.before
 * Action: throws on edit/write/notebookedit when first 5 lines include
 *         "AUTO-GENERATED by skillc"
 */

import type { Plugin } from "@opencode-ai/plugin"
import { readFile } from "node:fs/promises"
import { homedir } from "node:os"
import { isAbsolute, join, resolve } from "node:path"

const LOG_PREFIX = "[skillc-generated-guard]"
const DEBUG = process.env.ORCH_PLUGIN_DEBUG === "1"

const HEADER_LINE_LIMIT = 5
const AUTO_GENERATED_MARKER = "AUTO-GENERATED by skillc"
const GUARDED_TOOLS = new Set(["edit", "write", "notebookedit"])

function log(...args: any[]) {
  if (DEBUG) console.log(LOG_PREFIX, ...args)
}

function resolveFilePath(rawPath: string, directory: string): string {
  if (!rawPath) return rawPath

  if (rawPath === "~") {
    return homedir()
  }

  if (rawPath.startsWith("~/")) {
    return join(homedir(), rawPath.slice(2))
  }

  if (isAbsolute(rawPath)) {
    return rawPath
  }

  return resolve(directory, rawPath)
}

function extractFilePath(args: any): string | null {
  if (!args) return null
  return args.filePath || args.file_path || args.path || null
}

function extractSourceHint(headerLines: string[]): string | null {
  for (const line of headerLines) {
    const sourceMatch = line.match(/Source:\s*(.*?)\s*-->/)
    if (sourceMatch?.[1]) {
      return sourceMatch[1].trim()
    }

    const modifyMatch = line.match(/To modify:\s*edit files in\s*(.*?),\s*then run:/)
    if (modifyMatch?.[1]) {
      return modifyMatch[1].trim()
    }
  }

  return null
}

async function inspectHeader(filePath: string): Promise<{ blocked: boolean; sourceHint: string | null }> {
  try {
    const content = await readFile(filePath, "utf8")
    const headerLines = content.split(/\r?\n/).slice(0, HEADER_LINE_LIMIT)
    const blocked = headerLines.some((line) => line.includes(AUTO_GENERATED_MARKER))

    if (!blocked) {
      return { blocked: false, sourceHint: null }
    }

    return {
      blocked: true,
      sourceHint: extractSourceHint(headerLines),
    }
  } catch (err: any) {
    if (err?.code !== "ENOENT") {
      log("Failed to inspect file header:", filePath, err)
    }
    return { blocked: false, sourceHint: null }
  }
}

function buildBlockMessage(filePath: string, sourceHint: string | null): string {
  const guidance = sourceHint
    ? `Edit the .skillc source instead: ${sourceHint}`
    : "Edit the corresponding .skillc source directory instead."

  return [
    `Blocked direct edit of auto-generated file: ${filePath}`,
    `Reason: first ${HEADER_LINE_LIMIT} lines contain '${AUTO_GENERATED_MARKER}'.`,
    guidance,
    "Then recompile with 'skillc build' or 'skillc deploy'.",
  ].join("\n")
}

export const SkillcGeneratedGuardPlugin: Plugin = async ({ directory }) => {
  log("Plugin initialized, directory:", directory)

  return {
    "tool.execute.before": async (input, output) => {
      const tool = input.tool?.toLowerCase()
      if (!GUARDED_TOOLS.has(tool)) {
        return
      }

      const requestedPath = extractFilePath(output.args)
      if (!requestedPath) {
        return
      }

      const absolutePath = resolveFilePath(requestedPath, directory)
      const { blocked, sourceHint } = await inspectHeader(absolutePath)
      if (!blocked) {
        return
      }

      throw new Error(buildBlockMessage(absolutePath, sourceHint))
    },
  }
}
