#+title: Dylans Thoughts


* DONE i think what i'm sensing is the edge of my understanding when it comes
to the possibilities opencode has when it comes to their plugin system allowing us to hook into important steps in the system. like this instance for example. what i really want to know is what are we already doing in this vein already? what opportunities exist we should know about? how can we better mechanize the principles by plugging into opencode? do you have anything to add to this before we create an epic for it?
* DONE i'm still seeing the deprecation notices for kn. i think we integrated that into kb quick awhile ago? are we ready to finally complete the migration to kb quick?
* DONE is this orch-go-n5h2g.1 topic worthy of a new guide? we have multiple plugins now and are developing a deeper understanding of how the orchestration system should integrate with the execution layer
* TODO new ui design stuff
** TODO we've made small improvements related to worker agent real-time activity: /Users/dylanconlin/Screenshots/screenshot_2026-01-08_11-12-16.png

maybe use this skill? /Users/dylanconlin/orch-knowledge/skills/src/shared/design-principles

remaining pain points:
- default should be more legible
- tool calls/steps/reasoning etc should form a coherent, readable feed
- activity feed should also be accessible when agent isn't actively working.

examples from claude code:
/Users/dylanconlin/Screenshots/screenshot_2026-01-08_11-16-28.png
/Users/dylanconlin/Screenshots/screenshot_2026-01-08_11-17-50.png
** TODO figure out how to improve the ready queue display: /Users/dylanconlin/Screenshots/screenshot_2026-01-08_11-38-19.png
this is the type of issue where the approach i prefer is for the orchestrator to view the screenshot and then present a recommendation


check git history of /Users/dylanconlin/orch-knowledge for a skill related to creating ui mocks using a prompt-based approach with nano-banana pro

* noano
1) i think we've already started thinking about screenshot handling in the eco-system, should search for related artifacts/work
2) once i say it's good enough. i could tell the orchestrator or the worker i've signed off.
3) not sure   
4) currently just thinking of the orchestrator session as context dumping ground
5) agreed
