package main

import (
	"fmt"

	"github.com/spf13/cobra"
)

// GuardedFile represents a file type that has modification protocols
type GuardedFile struct {
	Name         string
	Pattern      string // How it's detected
	Protocol     string // What to do before editing
	Priority     int    // Higher = more specific
	ContentBased bool   // Requires reading file content
}

// guardedFiles defines all guarded file types
// Keep in sync with ~/.config/opencode/lib/guarded-files.ts
var guardedFiles = []GuardedFile{
	{
		Name:     "Principles",
		Pattern:  ".kb/principles.md",
		Priority: 110,
		Protocol: `~/.kb/principles.md requires following the principle-addition protocol.

Before editing:
  1. Ensure principle is tested (emerged from actual problem)
  2. Ensure principle is generative (guides future decisions)
  3. Ensure principle is not derivable from existing principles
  4. Ensure principle has teeth (violation causes real problems)

After editing:
  1. Add to Provenance table with date, what broke, evidence
  2. Check skills for updates needed
  3. Check guides for updates needed
  4. Check CLAUDE.md for updates needed
  5. Commit and push

See: ~/.kb/guides/principle-addition.md`,
	},
	{
		Name:         "skillc Generated",
		Pattern:      "Contains 'AUTO-GENERATED by skillc'",
		Priority:     100,
		ContentBased: true,
		Protocol: `This file is AUTO-GENERATED by skillc. DO NOT EDIT DIRECTLY.

To modify:
  1. Edit source files in the .skillc directory
  2. Run: skillc build or skillc deploy

Direct edits will be overwritten on next build.`,
	},
	{
		Name:     "Values",
		Pattern:  ".kb/values.md",
		Priority: 80,
		Protocol: `~/.kb/values.md is a foundational document.

Before editing:
  Consider if this is truly a value change or if it should be:
  - A principle (epistemic discipline) -> principles.md
  - A constraint (specific rule) -> kb quick constrain

Values guide *what matters*, principles guide *how to think*.`,
	},
	{
		Name:     "CLAUDE.md",
		Pattern:  "Any CLAUDE.md file",
		Priority: 70,
		Protocol: `CLAUDE.md files are loaded into every agent session.

Before editing:
  - Is this truly needed in EVERY session?
  - Could it be a skill instead (loaded on demand)?
  - Could it be in .kb/ (discoverable via kb context)?

Guidelines:
  - Keep concise (context window cost)
  - Use progressive disclosure
  - Reference detailed docs elsewhere`,
	},
	{
		Name:     "Decision Records",
		Pattern:  ".kb/decisions/*.md",
		Priority: 60,
		Protocol: `Decision records are immutable historical artifacts.

If decision is wrong:
  Create a NEW decision that supersedes this one.
  Add "Superseded-By:" field to old decision.

Never edit: The reasoning and evidence from the time of decision.
May update: Superseded-By field, Status field.`,
	},
	{
		Name:         "Auto-Generated",
		Pattern:      "Contains 'AUTO-GENERATED'",
		Priority:     10,
		ContentBased: true,
		Protocol: `This file contains AUTO-GENERATED content.

Look for comments indicating:
  - What generated this file
  - Where the source is
  - How to regenerate

Direct edits will likely be overwritten.`,
	},
	{
		Name:         "Protected Files",
		Pattern:      "Contains 'DO NOT EDIT'",
		Priority:     5,
		ContentBased: true,
		Protocol: `This file contains a "DO NOT EDIT" warning.

Look for instructions on how to properly modify this file.`,
	},
}

var guardedCmd = &cobra.Command{
	Use:    "guarded [name]",
	Short:  "List guarded files and their modification protocols",
	Hidden: true,
	Long: `List files that have modification protocols enforced by the guarded-files plugin.

These files require following specific procedures before editing. The guarded-files
OpenCode plugin surfaces these protocols when you attempt to edit protected files.

Examples:
  orch guarded              # List all guarded file types
  orch guarded principles   # Show protocol for principles.md
  orch guarded --verbose    # Show full protocols for all types`,
	RunE: func(cmd *cobra.Command, args []string) error {
		verbose, _ := cmd.Flags().GetBool("verbose")

		if len(args) > 0 {
			// Show specific guarded file
			name := args[0]
			for _, gf := range guardedFiles {
				if containsIgnoreCase(gf.Name, name) {
					printGuardedFile(gf, true)
					return nil
				}
			}
			return fmt.Errorf("unknown guarded file type: %s", name)
		}

		// List all guarded files
		fmt.Println("GUARDED FILES")
		fmt.Println("=============")
		fmt.Println()
		fmt.Println("Files with modification protocols enforced by guarded-files plugin.")
		fmt.Println("Run 'orch guarded <name>' for full protocol details.")
		fmt.Println()

		for _, gf := range guardedFiles {
			printGuardedFile(gf, verbose)
			fmt.Println()
		}

		fmt.Println("---")
		fmt.Println("Plugin source: ~/.config/opencode/lib/guarded-files.ts")

		return nil
	},
}

func printGuardedFile(gf GuardedFile, verbose bool) {
	detection := "path"
	if gf.ContentBased {
		detection = "content"
	}

	fmt.Printf("  %s (priority: %d, detection: %s)\n", gf.Name, gf.Priority, detection)
	fmt.Printf("    Pattern: %s\n", gf.Pattern)

	if verbose {
		fmt.Println()
		fmt.Println("    Protocol:")
		// Indent each line of the protocol
		for _, line := range splitLines(gf.Protocol) {
			fmt.Printf("      %s\n", line)
		}
	}
}

func containsIgnoreCase(s, substr string) bool {
	return len(substr) > 0 && len(s) >= len(substr) &&
		(equalFoldPrefix(s, substr) || containsIgnoreCase(s[1:], substr))
}

func equalFoldPrefix(s, prefix string) bool {
	if len(s) < len(prefix) {
		return false
	}
	for i := 0; i < len(prefix); i++ {
		c1, c2 := s[i], prefix[i]
		if c1 >= 'A' && c1 <= 'Z' {
			c1 += 'a' - 'A'
		}
		if c2 >= 'A' && c2 <= 'Z' {
			c2 += 'a' - 'A'
		}
		if c1 != c2 {
			return false
		}
	}
	return true
}

func splitLines(s string) []string {
	var lines []string
	start := 0
	for i := 0; i < len(s); i++ {
		if s[i] == '\n' {
			lines = append(lines, s[start:i])
			start = i + 1
		}
	}
	if start < len(s) {
		lines = append(lines, s[start:])
	}
	return lines
}

func init() {
	guardedCmd.Flags().BoolP("verbose", "v", false, "Show full protocols for all types")
	rootCmd.AddCommand(guardedCmd)
}
