package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// standalonePreCommitScript is the content of the standalone pre-commit accretion gate.
// It warns when staged files exceed size thresholds, catching unbounded file growth
// before it becomes a problem.
const standalonePreCommitScript = `#!/bin/bash
# =============================================================================
# Pre-commit: Accretion Gate (standalone)
# Generated by: orch harness init
# =============================================================================
#
# == WHY THIS GATE EXISTS ==
#
# In AI-assisted development, files grow fast. An agent adding 200 lines to an
# already-large file can push it past the point where other agents (or humans)
# can effectively reason about it. This gate catches unbounded growth early.
#
# == WHAT IT CHECKS ==
#
# For each staged file:
#   - HARD BLOCK: Files exceeding 1500 lines (exit 1, commit blocked)
#   - WARNING:    Files >800 lines gaining 30+ lines (informational)
#   - WARNING:    Files >600 lines gaining 50+ lines (informational)
#
# == HOW TO BYPASS ==
#
#   SKIP_ACCRETION_GATE=1 git commit -m "..."
#
# == WHAT TO DO WHEN BLOCKED ==
#
# 1. Extract a cohesive subset into a new file (e.g., helpers, types, handlers)
# 2. Split the file along domain boundaries
# 3. If the growth is justified, bypass with the env var above
#
# =============================================================================

# Escape hatch
if [ "${SKIP_ACCRETION_GATE}" = "1" ]; then
    echo "pre-commit: accretion gate bypassed (SKIP_ACCRETION_GATE=1)"
    exit 0
fi

HARD_LIMIT=1500
WARN_THRESHOLD_HIGH=800
WARN_LINES_HIGH=30
WARN_THRESHOLD_LOW=600
WARN_LINES_LOW=50

blocked=0
warned=0

# Check each staged file
while IFS=$'\t' read -r added removed file; do
    # Skip binary files (shown as - - by git)
    [ "$added" = "-" ] && continue
    # Skip deleted files
    [ -z "$file" ] && continue
    [ ! -f "$file" ] && continue

    total=$(wc -l < "$file" 2>/dev/null || echo 0)
    total=$(echo "$total" | tr -d ' ')
    net=$((added - removed))

    if [ "$total" -gt "$HARD_LIMIT" ]; then
        echo "BLOCKED: $file is $total lines (limit: $HARD_LIMIT)"
        echo "  Extract code into smaller files before committing."
        blocked=1
    elif [ "$total" -gt "$WARN_THRESHOLD_HIGH" ] && [ "$net" -ge "$WARN_LINES_HIGH" ]; then
        echo "WARNING: $file is $total lines (+$net net lines added)"
        warned=1
    elif [ "$total" -gt "$WARN_THRESHOLD_LOW" ] && [ "$net" -ge "$WARN_LINES_LOW" ]; then
        echo "WARNING: $file is $total lines (+$net net lines added)"
        warned=1
    fi
done < <(git diff --cached --numstat)

if [ "$blocked" -eq 1 ]; then
    echo ""
    echo "Commit blocked by accretion gate. Extract large files before committing."
    echo "Bypass: SKIP_ACCRETION_GATE=1 git commit -m '...'"
    exit 1
fi

if [ "$warned" -eq 1 ]; then
    echo "pre-commit: accretion gate passed (with warnings above)"
else
    echo "pre-commit: accretion gate passed"
fi
`

// removeTrailingExit removes a trailing 'exit 0' or 'exit $?' from a script
// so that appended code is reachable. Only removes the final exit statement —
// exit statements inside conditionals are preserved.
func removeTrailingExit(content string) string {
	trimmed := strings.TrimRight(content, " \t\n\r")
	lines := strings.Split(trimmed, "\n")
	if len(lines) == 0 {
		return content
	}
	last := strings.TrimSpace(lines[len(lines)-1])
	if last == "exit 0" || last == "exit $?" {
		return strings.Join(lines[:len(lines)-1], "\n") + "\n"
	}
	return content
}

// ensureBashShebang upgrades #!/bin/sh to #!/bin/bash.
// Process substitution (<()) requires bash and fails under sh.
func ensureBashShebang(content string) string {
	if strings.HasPrefix(content, "#!/bin/sh\n") {
		return "#!/bin/bash\n" + content[len("#!/bin/sh\n"):]
	}
	if strings.HasPrefix(content, "#!/bin/sh\r\n") {
		return "#!/bin/bash\r\n" + content[len("#!/bin/sh\r\n"):]
	}
	return content
}

// stripScriptShebang removes the shebang line from a script.
// Used when appending a script to an existing hook that already has a shebang.
func stripScriptShebang(content string) string {
	if strings.HasPrefix(content, "#!") {
		if idx := strings.Index(content, "\n"); idx >= 0 {
			return content[idx+1:]
		}
	}
	return content
}

// ensureStandalonePreCommitGate adds a self-contained accretion gate to .git/hooks/pre-commit.
// Unlike the full mode, this doesn't require the orch binary.
func ensureStandalonePreCommitGate(projectDir string) (*StepResult, error) {
	result := &StepResult{}

	hooksDir := filepath.Join(projectDir, ".git", "hooks")
	hookPath := filepath.Join(hooksDir, "pre-commit")

	marker := "Accretion Gate"

	// Check if already present
	data, err := os.ReadFile(hookPath)
	if err == nil && strings.Contains(string(data), marker) {
		result.AlreadyPresent = true
		return result, nil
	}

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return nil, fmt.Errorf("creating hooks dir: %w", err)
	}

	if os.IsNotExist(err) {
		// Create new pre-commit hook with the full standalone script
		if err := os.WriteFile(hookPath, []byte(standalonePreCommitScript), 0755); err != nil {
			return nil, fmt.Errorf("writing pre-commit: %w", err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("reading pre-commit: %w", err)
	} else {
		// Merge gate into existing hook:
		// 1. Upgrade shebang from sh to bash (process substitution requires bash)
		// 2. Remove trailing exit so appended gate code is reachable
		// 3. Strip shebang from gate script (existing hook already has one)
		content := ensureBashShebang(string(data))
		content = removeTrailingExit(content)
		gateBody := stripScriptShebang(standalonePreCommitScript)
		newContent := content + "\n# Accretion gate (added by orch harness init)\n" + gateBody

		if err := os.WriteFile(hookPath, []byte(newContent), 0755); err != nil {
			return nil, fmt.Errorf("writing pre-commit: %w", err)
		}
	}

	result.Created = true
	return result, nil
}

// ensurePreCommitGate adds the accretion gate to .git/hooks/pre-commit.
func ensurePreCommitGate(projectDir string) (*StepResult, error) {
	result := &StepResult{}

	hooksDir := filepath.Join(projectDir, ".git", "hooks")
	hookPath := filepath.Join(hooksDir, "pre-commit")

	accretionLine := "orch precommit accretion"

	// Check if already present
	data, err := os.ReadFile(hookPath)
	if err == nil && strings.Contains(string(data), accretionLine) {
		result.AlreadyPresent = true
		return result, nil
	}

	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return nil, fmt.Errorf("creating hooks dir: %w", err)
	}

	gate := "\n# Accretion warning gate (added by orch harness init)\norch precommit accretion 2>/dev/null || true\n"

	if os.IsNotExist(err) {
		// Create new pre-commit hook
		content := "#!/bin/bash\n" + gate
		if err := os.WriteFile(hookPath, []byte(content), 0755); err != nil {
			return nil, fmt.Errorf("writing pre-commit: %w", err)
		}
	} else if err != nil {
		return nil, fmt.Errorf("reading pre-commit: %w", err)
	} else {
		// Remove trailing exit so appended gate is reachable
		content := removeTrailingExit(string(data))
		newContent := content + gate

		if err := os.WriteFile(hookPath, []byte(newContent), 0755); err != nil {
			return nil, fmt.Errorf("writing pre-commit: %w", err)
		}
	}

	result.Created = true
	return result, nil
}
