package main

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/dylan-conlin/orch-go/pkg/opencode"
	"github.com/spf13/cobra"
)

var (
	tokensJSON bool
	tokensAll  bool // Include historical sessions (completed agents)
)

var tokensCmd = &cobra.Command{
	Use:   "tokens [session-id|beads-id]",
	Short: "Show token usage for sessions",
	Long: `Show detailed token usage for OpenCode sessions.

Without arguments, shows token usage for all active sessions.
With a session ID or beads ID, shows detailed breakdown for that session.

Token categories:
  - Input:     Tokens sent to the model (context + prompts)
  - Output:    Tokens generated by the model (responses)
  - Reasoning: Tokens used for extended thinking (Claude models)
  - Cache:     Tokens read from cache (reduces input costs)

Examples:
  orch tokens                      # Show all active sessions
  orch tokens --all                # Include completed sessions
  orch tokens --json               # Output as JSON
  orch tokens ses_abc123           # Show specific session
  orch tokens orch-go-3anf         # Show by beads ID`,
	RunE: func(cmd *cobra.Command, args []string) error {
		if len(args) > 0 {
			return runTokensDetail(args[0])
		}
		return runTokensSummary()
	},
}

func init() {
	tokensCmd.Flags().BoolVar(&tokensJSON, "json", false, "Output as JSON")
	tokensCmd.Flags().BoolVar(&tokensAll, "all", false, "Include historical/completed sessions")
	rootCmd.AddCommand(tokensCmd)
}

// TokensSummaryOutput represents the JSON output for tokens summary.
type TokensSummaryOutput struct {
	Sessions []TokensSessionInfo `json:"sessions"`
	Total    TokensTotal         `json:"total"`
}

// TokensSessionInfo represents token info for a single session.
type TokensSessionInfo struct {
	SessionID    string               `json:"session_id"`
	BeadsID      string               `json:"beads_id,omitempty"`
	Title        string               `json:"title"`
	Status       string               `json:"status"` // active, idle, completed
	Runtime      string               `json:"runtime"`
	Tokens       *opencode.TokenStats `json:"tokens"`
}

// TokensTotal represents aggregate token totals.
type TokensTotal struct {
	Sessions        int `json:"sessions"`
	InputTokens     int `json:"input_tokens"`
	OutputTokens    int `json:"output_tokens"`
	ReasoningTokens int `json:"reasoning_tokens,omitempty"`
	CacheReadTokens int `json:"cache_read_tokens,omitempty"`
	TotalTokens     int `json:"total_tokens"`
}

func runTokensSummary() error {
	client := opencode.NewClient(serverURL)
	now := time.Now()

	// List all sessions
	sessions, err := client.ListSessions("")
	if err != nil {
		return fmt.Errorf("failed to list sessions: %w", err)
	}

	const maxIdleTime = 30 * time.Minute
	var sessionInfos []TokensSessionInfo
	var total TokensTotal

	for _, s := range sessions {
		updatedAt := time.Unix(s.Time.Updated/1000, 0)
		createdAt := time.Unix(s.Time.Created/1000, 0)
		idleTime := now.Sub(updatedAt)

		// Skip old sessions unless --all is set
		if !tokensAll && idleTime > maxIdleTime {
			continue
		}

		// Extract beads ID from title
		beadsID := extractBeadsIDFromTitle(s.Title)
		if beadsID == "" && !tokensAll {
			// Skip non-orch sessions unless --all
			continue
		}

		// Determine status
		status := "active"
		if idleTime > 10*time.Minute {
			status = "idle"
		}
		if idleTime > maxIdleTime {
			status = "completed"
		}

		// Fetch token usage for this session
		tokens, err := client.GetSessionTokens(s.ID)
		if err != nil {
			// Skip sessions with token fetch errors
			continue
		}

		runtime := formatDuration(now.Sub(createdAt))

		info := TokensSessionInfo{
			SessionID: s.ID,
			BeadsID:   beadsID,
			Title:     s.Title,
			Status:    status,
			Runtime:   runtime,
			Tokens:    tokens,
		}
		sessionInfos = append(sessionInfos, info)

		// Aggregate totals
		if tokens != nil {
			total.InputTokens += tokens.InputTokens
			total.OutputTokens += tokens.OutputTokens
			total.ReasoningTokens += tokens.ReasoningTokens
			total.CacheReadTokens += tokens.CacheReadTokens
			total.TotalTokens += tokens.TotalTokens
		}
	}

	total.Sessions = len(sessionInfos)

	output := TokensSummaryOutput{
		Sessions: sessionInfos,
		Total:    total,
	}

	if tokensJSON {
		data, err := json.MarshalIndent(output, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to marshal JSON: %w", err)
		}
		fmt.Println(string(data))
		return nil
	}

	// Print human-readable output
	printTokensSummary(output)
	return nil
}

func printTokensSummary(output TokensSummaryOutput) {
	if len(output.Sessions) == 0 {
		fmt.Println("No sessions found")
		if !tokensAll {
			fmt.Println("Use --all to include completed sessions")
		}
		return
	}

	fmt.Printf("TOKEN USAGE SUMMARY (%d sessions)\n\n", len(output.Sessions))

	// Print sessions table
	fmt.Printf("  %-18s %-8s %-8s %-12s %-12s %-12s %s\n", "BEADS ID", "STATUS", "RUNTIME", "INPUT", "OUTPUT", "CACHE", "TOTAL")
	fmt.Printf("  %s\n", strings.Repeat("-", 90))

	for _, s := range output.Sessions {
		beadsID := s.BeadsID
		if beadsID == "" {
			beadsID = shortID(s.SessionID)
		}

		input := "-"
		output_tok := "-"
		cache := "-"
		total := "-"

		if s.Tokens != nil {
			input = formatTokenCount(s.Tokens.InputTokens)
			output_tok = formatTokenCount(s.Tokens.OutputTokens)
			if s.Tokens.CacheReadTokens > 0 {
				cache = formatTokenCount(s.Tokens.CacheReadTokens)
			}
			totalVal := s.Tokens.TotalTokens
			if totalVal == 0 {
				totalVal = s.Tokens.InputTokens + s.Tokens.OutputTokens
			}
			total = formatTokenCount(totalVal)
		}

		fmt.Printf("  %-18s %-8s %-8s %-12s %-12s %-12s %s\n",
			truncate(beadsID, 16),
			s.Status,
			s.Runtime,
			input,
			output_tok,
			cache,
			total)
	}

	// Print totals
	fmt.Printf("  %s\n", strings.Repeat("-", 90))
	fmt.Printf("  %-35s %-12s %-12s %-12s %s\n",
		"TOTAL",
		formatTokenCount(output.Total.InputTokens),
		formatTokenCount(output.Total.OutputTokens),
		formatTokenCount(output.Total.CacheReadTokens),
		formatTokenCount(output.Total.TotalTokens))
	fmt.Println()

	// Print cost estimate (rough estimate based on Claude pricing)
	// This is approximate - actual costs depend on model and caching
	if output.Total.TotalTokens > 0 {
		fmt.Println("Note: Token counts help monitor context usage. Actual costs vary by model and caching.")
	}
}

func runTokensDetail(identifier string) error {
	// Resolve identifier to session ID
	sessionID, err := resolveSessionID(serverURL, identifier)
	if err != nil {
		return fmt.Errorf("failed to resolve session: %w", err)
	}

	client := opencode.NewClient(serverURL)

	// Get session info
	session, err := client.GetSession(sessionID)
	if err != nil {
		return fmt.Errorf("failed to get session: %w", err)
	}

	// Get messages for detailed breakdown
	messages, err := client.GetMessages(sessionID)
	if err != nil {
		return fmt.Errorf("failed to get messages: %w", err)
	}

	// Aggregate tokens
	tokens := opencode.AggregateTokens(messages)

	if tokensJSON {
		output := struct {
			Session  *opencode.Session    `json:"session"`
			Messages int                  `json:"message_count"`
			Tokens   opencode.TokenStats  `json:"tokens"`
		}{
			Session:  session,
			Messages: len(messages),
			Tokens:   tokens,
		}
		data, err := json.MarshalIndent(output, "", "  ")
		if err != nil {
			return fmt.Errorf("failed to marshal JSON: %w", err)
		}
		fmt.Println(string(data))
		return nil
	}

	// Print human-readable output
	fmt.Printf("TOKEN USAGE: %s\n\n", session.Title)
	fmt.Printf("  Session ID:   %s\n", session.ID)
	fmt.Printf("  Messages:     %d\n", len(messages))
	fmt.Println()

	fmt.Println("BREAKDOWN")
	fmt.Printf("  %-20s %s\n", "Input tokens:", formatTokenCount(tokens.InputTokens))
	fmt.Printf("  %-20s %s\n", "Output tokens:", formatTokenCount(tokens.OutputTokens))
	if tokens.ReasoningTokens > 0 {
		fmt.Printf("  %-20s %s\n", "Reasoning tokens:", formatTokenCount(tokens.ReasoningTokens))
	}
	if tokens.CacheReadTokens > 0 {
		fmt.Printf("  %-20s %s\n", "Cache read tokens:", formatTokenCount(tokens.CacheReadTokens))
	}
	fmt.Printf("  %-20s %s\n", strings.Repeat("-", 16), strings.Repeat("-", 10))
	totalVal := tokens.TotalTokens
	if totalVal == 0 {
		totalVal = tokens.InputTokens + tokens.OutputTokens + tokens.ReasoningTokens
	}
	fmt.Printf("  %-20s %s\n", "Total:", formatTokenCount(totalVal))
	fmt.Println()

	// Show per-message breakdown if there are messages with tokens
	hasPerMsgTokens := false
	for _, msg := range messages {
		if msg.Info.Tokens != nil && (msg.Info.Tokens.Input > 0 || msg.Info.Tokens.Output > 0) {
			hasPerMsgTokens = true
			break
		}
	}

	if hasPerMsgTokens && len(messages) <= 20 {
		fmt.Println("PER-MESSAGE BREAKDOWN")
		fmt.Printf("  %-6s %-10s %-12s %-12s %s\n", "#", "ROLE", "INPUT", "OUTPUT", "REASONING")
		fmt.Printf("  %s\n", strings.Repeat("-", 60))

		for i, msg := range messages {
			if msg.Info.Tokens == nil {
				continue
			}
			t := msg.Info.Tokens
			reasoning := "-"
			if t.Reasoning > 0 {
				reasoning = formatTokenCount(t.Reasoning)
			}
			fmt.Printf("  %-6d %-10s %-12s %-12s %s\n",
				i+1,
				msg.Info.Role,
				formatTokenCount(t.Input),
				formatTokenCount(t.Output),
				reasoning)
		}
		fmt.Println()
	} else if len(messages) > 20 {
		fmt.Printf("(Showing summary only - %d messages in session)\n", len(messages))
	}

	return nil
}
