// Package tmux provides tmux session and window management for agent spawning.
// This file contains tmuxinator config generation functionality.
package tmux

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/dylan-conlin/orch-go/pkg/port"
)

// TmuxinatorConfig represents a tmuxinator configuration for a workers session.
type TmuxinatorConfig struct {
	Name       string            // Session name (e.g., "workers-snap")
	Root       string            // Project root directory
	Project    string            // Project name (e.g., "snap")
	ServerPane []ServerPane      // Server panes configuration
	Ports      []port.Allocation // Port allocations for this project
}

// ServerPane represents a pane in the servers window.
type ServerPane struct {
	Command string // Command to run (e.g., "bun run dev --port 5174")
	Service string // Service name (e.g., "web", "api")
	Port    int    // Allocated port
}

// tmuxinatorTemplate is the template for generating workers-{project}.yml files.
const tmuxinatorTemplate = `# Auto-generated by orch spawn
# Per-project workers session for {{.Project}}
name: {{.Name}}
root: {{.Root}}

# Start focused on servers window (for dev servers)
startup_window: servers

windows:
  - servers:
{{- if gt (len .ServerPane) 1}}
      layout: even-horizontal
{{- end}}
      panes:
{{- if eq (len .ServerPane) 0}}
        - # Dev servers (npm run dev, etc.)
{{- else}}
{{- range .ServerPane}}
        - {{.Command}}
{{- end}}
{{- end}}
`

// GenerateTmuxinatorConfig generates a tmuxinator configuration for a project.
// It queries the port registry for allocated ports and builds server pane commands.
func GenerateTmuxinatorConfig(projectName, projectDir string, portRegistry *port.Registry) (*TmuxinatorConfig, error) {
	// Get port allocations for this project
	var allocations []port.Allocation
	if portRegistry != nil {
		allocations = portRegistry.ListByProject(projectName)
	}

	// Build server panes from allocations
	serverPanes := make([]ServerPane, 0)
	for _, alloc := range allocations {
		pane := ServerPane{
			Command: buildServerCommand(alloc),
			Service: alloc.Service,
			Port:    alloc.Port,
		}
		serverPanes = append(serverPanes, pane)
	}

	config := &TmuxinatorConfig{
		Name:       GetWorkersSessionName(projectName),
		Root:       projectDir,
		Project:    projectName,
		ServerPane: serverPanes,
		Ports:      allocations,
	}

	return config, nil
}

// buildServerCommand constructs the appropriate dev server command based on allocation.
func buildServerCommand(alloc port.Allocation) string {
	switch alloc.Purpose {
	case port.PurposeVite:
		// Vite/web dev servers typically use: bun run dev --port N or npm run dev -- --port N
		return fmt.Sprintf("bun run dev --port %d", alloc.Port)
	case port.PurposeAPI:
		// API servers - more generic, often just need the port in environment
		return fmt.Sprintf("# %s server on port %d", alloc.Service, alloc.Port)
	default:
		return fmt.Sprintf("# %s on port %d", alloc.Service, alloc.Port)
	}
}

// RenderTmuxinatorConfig renders the configuration to YAML.
func (c *TmuxinatorConfig) Render() (string, error) {
	tmpl, err := template.New("tmuxinator").Parse(tmuxinatorTemplate)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, c); err != nil {
		return "", fmt.Errorf("failed to render template: %w", err)
	}

	return buf.String(), nil
}

// WriteTmuxinatorConfig writes the configuration to the tmuxinator config directory.
// Returns the path to the written file.
func (c *TmuxinatorConfig) Write() (string, error) {
	content, err := c.Render()
	if err != nil {
		return "", err
	}

	// Get tmuxinator config directory
	configDir := TmuxinatorConfigDir()
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return "", fmt.Errorf("failed to create config directory: %w", err)
	}

	// Write file
	filename := fmt.Sprintf("%s.yml", c.Name)
	configPath := filepath.Join(configDir, filename)
	if err := os.WriteFile(configPath, []byte(content), 0644); err != nil {
		return "", fmt.Errorf("failed to write config: %w", err)
	}

	return configPath, nil
}

// TmuxinatorConfigDir returns the tmuxinator configuration directory.
func TmuxinatorConfigDir() string {
	home, _ := os.UserHomeDir()
	return filepath.Join(home, ".tmuxinator")
}

// TmuxinatorConfigPath returns the path for a specific workers config.
func TmuxinatorConfigPath(projectName string) string {
	return filepath.Join(TmuxinatorConfigDir(), fmt.Sprintf("workers-%s.yml", projectName))
}

// UpdateTmuxinatorConfig updates or creates a tmuxinator config for a project.
// This is the main entry point for updating configs with port allocations.
func UpdateTmuxinatorConfig(projectName, projectDir string) (string, error) {
	// Load port registry
	registry, err := port.New("")
	if err != nil {
		return "", fmt.Errorf("failed to load port registry: %w", err)
	}

	// Generate config
	config, err := GenerateTmuxinatorConfig(projectName, projectDir, registry)
	if err != nil {
		return "", fmt.Errorf("failed to generate config: %w", err)
	}

	// Write config
	return config.Write()
}

// EnsureTmuxinatorConfig ensures a tmuxinator config exists for the project.
// If it exists, updates it with current port allocations.
// If it doesn't exist, creates it.
func EnsureTmuxinatorConfig(projectName, projectDir string) (string, error) {
	return UpdateTmuxinatorConfig(projectName, projectDir)
}
