package tmux

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dylan-conlin/orch-go/pkg/port"
)

func TestGenerateTmuxinatorConfig_NoPorts(t *testing.T) {
	// Test with nil registry (no ports)
	config, err := GenerateTmuxinatorConfig("testproject", "/path/to/project", nil)
	if err != nil {
		t.Fatalf("GenerateTmuxinatorConfig() error = %v", err)
	}

	if config.Name != "workers-testproject" {
		t.Errorf("config.Name = %q, want %q", config.Name, "workers-testproject")
	}
	if config.Root != "/path/to/project" {
		t.Errorf("config.Root = %q, want %q", config.Root, "/path/to/project")
	}
	if config.Project != "testproject" {
		t.Errorf("config.Project = %q, want %q", config.Project, "testproject")
	}
	if len(config.ServerPane) != 0 {
		t.Errorf("config.ServerPane length = %d, want 0", len(config.ServerPane))
	}
}

func TestGenerateTmuxinatorConfig_WithPorts(t *testing.T) {
	// Create a temporary port registry
	tmpDir := t.TempDir()
	registryPath := filepath.Join(tmpDir, "ports.yaml")

	reg, err := port.New(registryPath)
	if err != nil {
		t.Fatalf("Failed to create port registry: %v", err)
	}

	// Allocate some ports
	_, err = reg.Allocate("snap", "web", port.PurposeVite)
	if err != nil {
		t.Fatalf("Failed to allocate vite port: %v", err)
	}
	_, err = reg.Allocate("snap", "api", port.PurposeAPI)
	if err != nil {
		t.Fatalf("Failed to allocate api port: %v", err)
	}

	// Generate config
	config, err := GenerateTmuxinatorConfig("snap", "/path/to/snap", reg)
	if err != nil {
		t.Fatalf("GenerateTmuxinatorConfig() error = %v", err)
	}

	if config.Name != "workers-snap" {
		t.Errorf("config.Name = %q, want %q", config.Name, "workers-snap")
	}
	if len(config.ServerPane) != 2 {
		t.Errorf("config.ServerPane length = %d, want 2", len(config.ServerPane))
	}

	// Check that panes have correct ports
	for _, pane := range config.ServerPane {
		if pane.Service == "web" && pane.Port != 5173 {
			t.Errorf("web service port = %d, want 5173", pane.Port)
		}
		if pane.Service == "api" && pane.Port != 3333 {
			t.Errorf("api service port = %d, want 3333", pane.Port)
		}
	}
}

func TestTmuxinatorConfig_Render_NoPorts(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:       "workers-snap",
		Root:       "/path/to/snap",
		Project:    "snap",
		ServerPane: []ServerPane{},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Check key elements
	expectedParts := []string{
		"# Auto-generated by orch spawn",
		"name: workers-snap",
		"root: /path/to/snap",
		"startup_window: servers",
		"- servers:",
		"# Dev servers (npm run dev, etc.)",
	}

	for _, part := range expectedParts {
		if !strings.Contains(rendered, part) {
			t.Errorf("Render() output missing: %q", part)
		}
	}

	// Should NOT have layout: even-horizontal with no panes
	if strings.Contains(rendered, "layout: even-horizontal") {
		t.Error("Render() should not include layout: even-horizontal with no panes")
	}
}

func TestTmuxinatorConfig_Render_WithPorts(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:    "workers-snap",
		Root:    "/path/to/snap",
		Project: "snap",
		ServerPane: []ServerPane{
			{Command: "bun run dev --port 5173", Service: "web", Port: 5173},
			{Command: "# api server on port 3333", Service: "api", Port: 3333},
		},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Check key elements
	expectedParts := []string{
		"# Auto-generated by orch spawn",
		"name: workers-snap",
		"root: /path/to/snap",
		"layout: even-horizontal", // Should have layout with 2+ panes
		"- bun run dev --port 5173",
		"- # api server on port 3333",
	}

	for _, part := range expectedParts {
		if !strings.Contains(rendered, part) {
			t.Errorf("Render() output missing: %q\nGot:\n%s", part, rendered)
		}
	}

	// Should NOT have the default placeholder comment
	if strings.Contains(rendered, "# Dev servers (npm run dev, etc.)") {
		t.Error("Render() should not include default comment when panes are defined")
	}
}

func TestTmuxinatorConfig_Render_SinglePane(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:    "workers-snap",
		Root:    "/path/to/snap",
		Project: "snap",
		ServerPane: []ServerPane{
			{Command: "bun run dev --port 5173", Service: "web", Port: 5173},
		},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Should NOT have layout: even-horizontal with single pane
	if strings.Contains(rendered, "layout: even-horizontal") {
		t.Error("Render() should not include layout: even-horizontal with single pane")
	}

	// Should have the pane command
	if !strings.Contains(rendered, "- bun run dev --port 5173") {
		t.Error("Render() should include pane command")
	}
}

func TestTmuxinatorConfig_Write(t *testing.T) {
	// Use a temporary directory
	tmpDir := t.TempDir()

	// Override the config dir for testing
	oldHome := os.Getenv("HOME")
	os.Setenv("HOME", tmpDir)
	defer os.Setenv("HOME", oldHome)

	config := &TmuxinatorConfig{
		Name:       "workers-test",
		Root:       "/path/to/test",
		Project:    "test",
		ServerPane: []ServerPane{},
	}

	path, err := config.Write()
	if err != nil {
		t.Fatalf("Write() error = %v", err)
	}

	// Check file was created
	expectedPath := filepath.Join(tmpDir, ".tmuxinator", "workers-test.yml")
	if path != expectedPath {
		t.Errorf("Write() path = %q, want %q", path, expectedPath)
	}

	// Check file exists and has content
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("Failed to read written file: %v", err)
	}

	if !strings.Contains(string(content), "name: workers-test") {
		t.Error("Written file missing expected content")
	}
}

func TestBuildServerCommand(t *testing.T) {
	tests := []struct {
		alloc port.Allocation
		want  string
	}{
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "web",
				Port:    5173,
				Purpose: port.PurposeVite,
			},
			want: "bun run dev --port 5173",
		},
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "api",
				Port:    3333,
				Purpose: port.PurposeAPI,
			},
			want: "# api server on port 3333",
		},
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "custom",
				Port:    8080,
				Purpose: "custom",
			},
			want: "# custom on port 8080",
		},
	}

	for _, tt := range tests {
		t.Run(tt.alloc.Service, func(t *testing.T) {
			got := buildServerCommand(tt.alloc)
			if got != tt.want {
				t.Errorf("buildServerCommand() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTmuxinatorConfigPath(t *testing.T) {
	home, _ := os.UserHomeDir()
	expected := filepath.Join(home, ".tmuxinator", "workers-snap.yml")
	got := TmuxinatorConfigPath("snap")
	if got != expected {
		t.Errorf("TmuxinatorConfigPath() = %q, want %q", got, expected)
	}
}

func TestTmuxinatorConfigDir(t *testing.T) {
	home, _ := os.UserHomeDir()
	expected := filepath.Join(home, ".tmuxinator")
	got := TmuxinatorConfigDir()
	if got != expected {
		t.Errorf("TmuxinatorConfigDir() = %q, want %q", got, expected)
	}
}

func TestParseProcfile(t *testing.T) {
	// Create temp directory with a Procfile
	tmpDir := t.TempDir()
	procfilePath := filepath.Join(tmpDir, "Procfile")

	procfileContent := `# Comment line
api: orch serve
web: cd web && bun run dev
opencode: env -u ANTHROPIC_API_KEY ~/.bun/bin/opencode serve --port 4096

# Another comment
`
	if err := os.WriteFile(procfilePath, []byte(procfileContent), 0644); err != nil {
		t.Fatalf("Failed to write Procfile: %v", err)
	}

	commands := parseProcfile(tmpDir)
	if commands == nil {
		t.Fatal("parseProcfile() returned nil")
	}

	// Check parsed commands
	tests := []struct {
		service string
		want    string
	}{
		{"api", "orch serve"},
		{"web", "cd web && bun run dev"},
		{"opencode", "env -u ANTHROPIC_API_KEY ~/.bun/bin/opencode serve --port 4096"},
	}

	for _, tt := range tests {
		got, ok := commands[tt.service]
		if !ok {
			t.Errorf("parseProcfile() missing service %q", tt.service)
			continue
		}
		if got != tt.want {
			t.Errorf("parseProcfile()[%q] = %q, want %q", tt.service, got, tt.want)
		}
	}

	// Should only have 3 services (comments and blank lines ignored)
	if len(commands) != 3 {
		t.Errorf("parseProcfile() returned %d services, want 3", len(commands))
	}
}

func TestParseProcfile_NotExists(t *testing.T) {
	// Test with non-existent Procfile
	tmpDir := t.TempDir()
	commands := parseProcfile(tmpDir)
	if commands != nil {
		t.Error("parseProcfile() should return nil when Procfile doesn't exist")
	}
}

func TestOrchGoProcfile_HasDoctorDaemon(t *testing.T) {
	// Test that the actual orch-go Procfile includes the doctor daemon entry
	// Find orch-go project root (where Procfile is)
	projectDir := findOrchGoRoot(t)

	commands := parseProcfile(projectDir)
	if commands == nil {
		t.Fatal("parseProcfile() returned nil for orch-go Procfile")
	}

	// Verify doctor daemon entry exists
	doctorCmd, ok := commands["doctor"]
	if !ok {
		t.Error("Procfile missing 'doctor' service entry")
	}

	want := "orch doctor --daemon"
	if doctorCmd != want {
		t.Errorf("doctor service = %q, want %q", doctorCmd, want)
	}
}

// findOrchGoRoot finds the orch-go project root directory
func findOrchGoRoot(t *testing.T) string {
	t.Helper()

	// Start from current file's directory and walk up
	dir, err := filepath.Abs(".")
	if err != nil {
		t.Fatalf("Failed to get absolute path: %v", err)
	}

	for {
		procfilePath := filepath.Join(dir, "Procfile")
		if _, err := os.Stat(procfilePath); err == nil {
			// Found Procfile - verify it's the orch-go one by checking for go.mod
			goModPath := filepath.Join(dir, "go.mod")
			if _, err := os.Stat(goModPath); err == nil {
				return dir
			}
		}

		parent := filepath.Dir(dir)
		if parent == dir {
			t.Fatal("Could not find orch-go project root with Procfile")
		}
		dir = parent
	}
}

func TestGenerateTmuxinatorConfig_WithProcfile(t *testing.T) {
	// Create a temporary directory with port registry and Procfile
	tmpDir := t.TempDir()
	registryPath := filepath.Join(tmpDir, "ports.yaml")

	// Create port registry
	reg, err := port.New(registryPath)
	if err != nil {
		t.Fatalf("Failed to create port registry: %v", err)
	}

	// Allocate ports
	_, err = reg.Allocate("myproject", "web", port.PurposeVite)
	if err != nil {
		t.Fatalf("Failed to allocate vite port: %v", err)
	}
	_, err = reg.Allocate("myproject", "api", port.PurposeAPI)
	if err != nil {
		t.Fatalf("Failed to allocate api port: %v", err)
	}

	// Create project directory with Procfile
	projectDir := filepath.Join(tmpDir, "myproject")
	if err := os.MkdirAll(projectDir, 0755); err != nil {
		t.Fatalf("Failed to create project dir: %v", err)
	}

	procfileContent := `api: go run ./cmd/server
web: cd frontend && npm run dev
`
	procfilePath := filepath.Join(projectDir, "Procfile")
	if err := os.WriteFile(procfilePath, []byte(procfileContent), 0644); err != nil {
		t.Fatalf("Failed to write Procfile: %v", err)
	}

	// Generate config
	config, err := GenerateTmuxinatorConfig("myproject", projectDir, reg)
	if err != nil {
		t.Fatalf("GenerateTmuxinatorConfig() error = %v", err)
	}

	// Check that Procfile commands are used
	for _, pane := range config.ServerPane {
		switch pane.Service {
		case "web":
			// Should use Procfile command, not auto-generated
			if pane.Command != "cd frontend && npm run dev" {
				t.Errorf("web pane.Command = %q, want %q (from Procfile)", pane.Command, "cd frontend && npm run dev")
			}
		case "api":
			// Should use Procfile command, not auto-generated
			if pane.Command != "go run ./cmd/server" {
				t.Errorf("api pane.Command = %q, want %q (from Procfile)", pane.Command, "go run ./cmd/server")
			}
		}
	}
}
