package tmux

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/dylan-conlin/orch-go/pkg/port"
)

func TestGenerateTmuxinatorConfig_NoPorts(t *testing.T) {
	// Test with nil registry (no ports)
	config, err := GenerateTmuxinatorConfig("testproject", "/path/to/project", nil)
	if err != nil {
		t.Fatalf("GenerateTmuxinatorConfig() error = %v", err)
	}

	if config.Name != "workers-testproject" {
		t.Errorf("config.Name = %q, want %q", config.Name, "workers-testproject")
	}
	if config.Root != "/path/to/project" {
		t.Errorf("config.Root = %q, want %q", config.Root, "/path/to/project")
	}
	if config.Project != "testproject" {
		t.Errorf("config.Project = %q, want %q", config.Project, "testproject")
	}
	if len(config.ServerPane) != 0 {
		t.Errorf("config.ServerPane length = %d, want 0", len(config.ServerPane))
	}
}

func TestGenerateTmuxinatorConfig_WithPorts(t *testing.T) {
	// Create a temporary port registry
	tmpDir := t.TempDir()
	registryPath := filepath.Join(tmpDir, "ports.yaml")

	reg, err := port.New(registryPath)
	if err != nil {
		t.Fatalf("Failed to create port registry: %v", err)
	}

	// Allocate some ports
	_, err = reg.Allocate("snap", "web", port.PurposeVite)
	if err != nil {
		t.Fatalf("Failed to allocate vite port: %v", err)
	}
	_, err = reg.Allocate("snap", "api", port.PurposeAPI)
	if err != nil {
		t.Fatalf("Failed to allocate api port: %v", err)
	}

	// Generate config
	config, err := GenerateTmuxinatorConfig("snap", "/path/to/snap", reg)
	if err != nil {
		t.Fatalf("GenerateTmuxinatorConfig() error = %v", err)
	}

	if config.Name != "workers-snap" {
		t.Errorf("config.Name = %q, want %q", config.Name, "workers-snap")
	}
	if len(config.ServerPane) != 2 {
		t.Errorf("config.ServerPane length = %d, want 2", len(config.ServerPane))
	}

	// Check that panes have correct ports
	for _, pane := range config.ServerPane {
		if pane.Service == "web" && pane.Port != 5173 {
			t.Errorf("web service port = %d, want 5173", pane.Port)
		}
		if pane.Service == "api" && pane.Port != 3333 {
			t.Errorf("api service port = %d, want 3333", pane.Port)
		}
	}
}

func TestTmuxinatorConfig_Render_NoPorts(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:       "workers-snap",
		Root:       "/path/to/snap",
		Project:    "snap",
		ServerPane: []ServerPane{},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Check key elements
	expectedParts := []string{
		"# Auto-generated by orch spawn",
		"name: workers-snap",
		"root: /path/to/snap",
		"startup_window: servers",
		"- servers:",
		"# Dev servers (npm run dev, etc.)",
	}

	for _, part := range expectedParts {
		if !strings.Contains(rendered, part) {
			t.Errorf("Render() output missing: %q", part)
		}
	}

	// Should NOT have layout: even-horizontal with no panes
	if strings.Contains(rendered, "layout: even-horizontal") {
		t.Error("Render() should not include layout: even-horizontal with no panes")
	}
}

func TestTmuxinatorConfig_Render_WithPorts(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:    "workers-snap",
		Root:    "/path/to/snap",
		Project: "snap",
		ServerPane: []ServerPane{
			{Command: "bun run dev --port 5173", Service: "web", Port: 5173},
			{Command: "# api server on port 3333", Service: "api", Port: 3333},
		},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Check key elements
	expectedParts := []string{
		"# Auto-generated by orch spawn",
		"name: workers-snap",
		"root: /path/to/snap",
		"layout: even-horizontal", // Should have layout with 2+ panes
		"- bun run dev --port 5173",
		"- # api server on port 3333",
	}

	for _, part := range expectedParts {
		if !strings.Contains(rendered, part) {
			t.Errorf("Render() output missing: %q\nGot:\n%s", part, rendered)
		}
	}

	// Should NOT have the default placeholder comment
	if strings.Contains(rendered, "# Dev servers (npm run dev, etc.)") {
		t.Error("Render() should not include default comment when panes are defined")
	}
}

func TestTmuxinatorConfig_Render_SinglePane(t *testing.T) {
	config := &TmuxinatorConfig{
		Name:    "workers-snap",
		Root:    "/path/to/snap",
		Project: "snap",
		ServerPane: []ServerPane{
			{Command: "bun run dev --port 5173", Service: "web", Port: 5173},
		},
	}

	rendered, err := config.Render()
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	// Should NOT have layout: even-horizontal with single pane
	if strings.Contains(rendered, "layout: even-horizontal") {
		t.Error("Render() should not include layout: even-horizontal with single pane")
	}

	// Should have the pane command
	if !strings.Contains(rendered, "- bun run dev --port 5173") {
		t.Error("Render() should include pane command")
	}
}

func TestTmuxinatorConfig_Write(t *testing.T) {
	// Use a temporary directory
	tmpDir := t.TempDir()

	// Override the config dir for testing
	oldHome := os.Getenv("HOME")
	os.Setenv("HOME", tmpDir)
	defer os.Setenv("HOME", oldHome)

	config := &TmuxinatorConfig{
		Name:       "workers-test",
		Root:       "/path/to/test",
		Project:    "test",
		ServerPane: []ServerPane{},
	}

	path, err := config.Write()
	if err != nil {
		t.Fatalf("Write() error = %v", err)
	}

	// Check file was created
	expectedPath := filepath.Join(tmpDir, ".tmuxinator", "workers-test.yml")
	if path != expectedPath {
		t.Errorf("Write() path = %q, want %q", path, expectedPath)
	}

	// Check file exists and has content
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("Failed to read written file: %v", err)
	}

	if !strings.Contains(string(content), "name: workers-test") {
		t.Error("Written file missing expected content")
	}
}

func TestBuildServerCommand(t *testing.T) {
	tests := []struct {
		alloc port.Allocation
		want  string
	}{
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "web",
				Port:    5173,
				Purpose: port.PurposeVite,
			},
			want: "bun run dev --port 5173",
		},
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "api",
				Port:    3333,
				Purpose: port.PurposeAPI,
			},
			want: "# api server on port 3333",
		},
		{
			alloc: port.Allocation{
				Project: "snap",
				Service: "custom",
				Port:    8080,
				Purpose: "custom",
			},
			want: "# custom on port 8080",
		},
	}

	for _, tt := range tests {
		t.Run(tt.alloc.Service, func(t *testing.T) {
			got := buildServerCommand(tt.alloc)
			if got != tt.want {
				t.Errorf("buildServerCommand() = %q, want %q", got, tt.want)
			}
		})
	}
}

func TestTmuxinatorConfigPath(t *testing.T) {
	home, _ := os.UserHomeDir()
	expected := filepath.Join(home, ".tmuxinator", "workers-snap.yml")
	got := TmuxinatorConfigPath("snap")
	if got != expected {
		t.Errorf("TmuxinatorConfigPath() = %q, want %q", got, expected)
	}
}

func TestTmuxinatorConfigDir(t *testing.T) {
	home, _ := os.UserHomeDir()
	expected := filepath.Join(home, ".tmuxinator")
	got := TmuxinatorConfigDir()
	if got != expected {
		t.Errorf("TmuxinatorConfigDir() = %q, want %q", got, expected)
	}
}
