#!/usr/bin/env python3
"""
principlec build - Compile modular principles into principles.md

Reads principles.yaml manifest and concatenates principle files
in the specified order with category headers.
"""

import os
import sys
import yaml
import hashlib
from datetime import datetime
from pathlib import Path

PRINCIPLEC_DIR = Path(__file__).parent
SRC_DIR = PRINCIPLEC_DIR / "src"
MANIFEST = PRINCIPLEC_DIR / "principles.yaml"
OUTPUT = Path.home() / ".kb" / "principles.md"


def compute_checksum(content: str) -> str:
    """Compute short checksum for content."""
    return hashlib.md5(content.encode()).hexdigest()[:12]


def load_manifest() -> dict:
    """Load and validate the principles manifest."""
    with open(MANIFEST) as f:
        return yaml.safe_load(f)


def load_principle(category: str, name: str) -> str:
    """Load a single principle file."""
    path = SRC_DIR / category / f"{name}.md"
    if not path.exists():
        print(f"WARNING: Principle not found: {path}", file=sys.stderr)
        return f"<!-- MISSING: {category}/{name}.md -->\n"
    return path.read_text()


def load_provenance() -> str:
    """Load provenance section if it exists."""
    path = SRC_DIR / "provenance.md"
    if path.exists():
        return path.read_text()
    return ""


def build_header(checksum: str) -> str:
    """Generate the auto-generated header."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""<!-- AUTO-GENERATED by principlec -->
<!-- Checksum: {checksum} -->
<!-- Source: ~/.kb/.principlec/ -->
<!-- To modify: edit files in src/, then run: principlec build -->
<!-- Last compiled: {timestamp} -->

"""


def build_intro(manifest: dict) -> str:
    """Build the intro section."""
    return f"""# Meta-Orchestration Principles

**Purpose:** Foundational values that guide design decisions across the system.

**When to reference:** Before making architectural choices. When evaluating trade-offs. When something feels wrong but you can't articulate why.

---

"""


def build_category(category: dict) -> str:
    """Build a single category section."""
    lines = []
    lines.append(f"## {category['title']}\n")
    lines.append(f"_{category['description']}_\n")

    # Optional framing text between description and principles
    if 'framing' in category:
        lines.append(category['framing'].rstrip() + "\n")

    for principle_name in category['principles']:
        content = load_principle(category['name'], principle_name)
        lines.append(content)
        if not content.endswith("\n\n"):
            lines.append("\n")
        lines.append("---\n\n")

    return "\n".join(lines)


def build_provenance_section() -> str:
    """Load provenance section if it exists."""
    path = SRC_DIR / "provenance.md"
    if path.exists():
        return path.read_text() + "\n"
    return ""


def build_applying_section() -> str:
    """Build the 'Applying Principles' section."""
    return """## Applying Principles and Values

**Principles** (`~/.kb/principles.md`) guide *how to think* - epistemic discipline.
**Values** (`~/.kb/values.md`) guide *what matters* - ethical discipline.

**When making decisions:**

- Cite which principle guides your reasoning
- When principles conflict, provenance wins (most foundational), then session amnesia
- If no principle applies, you may be discovering a new one

**When something feels wrong:**

- Check if a principle is being violated
- Check if concepts are conflated (evolve by distinction)
- Check if evidence hierarchy is inverted (treating artifacts as truth)
- Check if you're relying on reminders instead of gates
- Check if you're solving compliance when the real problem is coordination

**When adding new principles:**

- Must be tested (emerged from actual problems)
- Must be generative (guides future decisions)
- Must not be derivable from existing principles
- Must have teeth (violation causes real problems)

**The test for new principles:** Can you trace it to a specific failure? If not, it's not a principle yet.

---

"""


def build() -> str:
    """Build the complete principles.md content."""
    manifest = load_manifest()

    parts = []
    parts.append(build_intro(manifest))

    for category in manifest['categories']:
        parts.append(build_category(category))

    parts.append(build_applying_section())
    parts.append(build_provenance_section())

    # Compute checksum of content (before adding header)
    content = "".join(parts)
    checksum = compute_checksum(content)

    # Add header at the beginning
    final = build_header(checksum) + content

    return final


def main():
    """Main entry point."""
    content = build()

    # Write output
    OUTPUT.write_text(content)

    # Report
    line_count = content.count('\n')
    print(f"✓ Compiled {OUTPUT}")
    print(f"  {line_count} lines")


if __name__ == "__main__":
    main()
